### ISSUE TITLE
POIProxy operates on Windows server?

### ISSUE THREAD

**Issue by gkouk** [Prodevelop/POIProxy#3]
Hello,
I want to ask if POIProxy service operates on Windows Server 2012? Because I made all the required software installation and deploy steps but when I try to browse the panoramio sample at http://localhost:8080/poiproxy I get an "Internal Server Error" with no error in tomcat log files. I have to mention that I have already installed POIProxy on an Ubuntu server with success.
Thank you in advance,
George

**Comment by alrocar** [comment]
Sorry, we have not tested it on Windows...

**Comment by gkouk** [comment]
I assumed it will operates, because it's java. I tried it in windows server 2012 and although the "mvn clean install" command ended with success when I browsed the panoramio sample at http://localhost:8080/poiproxy I got the "Internal Server Error".
It's a pity not to operate on Windows too, because it's a very good service!
Thank you for your time,
George
